services:
    tgp-web:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        command: sh -c 'exec /var/www/tmp/.docker/docker-entrypoint.sh'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
            - '5173:5173'
        volumes:
            - '.:/var/www/html'
        networks:
            - main
        depends_on:
            mysql:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
            elasticsearch:
                condition: service_healthy
            redis:
                condition: service_healthy
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'volume-mysql:/var/lib/mysql'
        networks:
            - main
        healthcheck:
            test: [ "CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD" ]
            interval: 5s
            timeout: 5s
            retries: 10
    rabbitmq:
        image: 'rabbitmq:4.2.5-management'
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            RABBITMQ_DEFAULT_USER: root
            RABBITMQ_DEFAULT_PASS: pass
        networks:
            - main
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "ping"]
            interval: 5s
            timeout: 5s
            retries: 10
    tgp-worker:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        command: php bin/worker.php
        volumes:
            - '.:/var/www/html'
        networks:
            - main
        depends_on:
            rabbitmq:
                condition: service_healthy
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:9.3.2'
        ports:
            - '9200:9200'
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xlog:disable -Xlog:all=warning:stderr:utctime,level,tags -Xlog:gc=debug:stderr:utctime
            - xpack.security.enabled=false
        volumes:
            - 'volume-elasticsearch:/etc/localtime:ro'
            - 'volume-elasticsearch-data:/usr/share/elasticsearch/data'
        networks:
            - main
        ulimits:
            memlock:
                soft: -1
                hard: -1
        healthcheck:
            test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status'" ]
            interval: 10s
            timeout: 10s
            retries: 20
    kibana:
        image: 'docker.elastic.co/kibana/kibana:9.3.2'
        restart: unless-stopped
        ports:
            - '5601:5601'
        volumes:
            - 'volume-kibana:/etc/localtime:ro'
            - 'volume-kibana-data:/usr/share/kibana/data'
        networks:
            - main
        depends_on:
            elasticsearch:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'"]
            retries: 10
            timeout: 10s
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'volume-redis:/data'
        networks:
            - main
        mem_limit: 1G
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    main:
        driver: bridge
volumes:
    volume-mysql:
        driver: local
    volume-elasticsearch:
        driver: local
    volume-elasticsearch-data:
        driver: local
    volume-kibana:
        driver: local
    volume-kibana-data:
        driver: local
    volume-redis:
        driver: local
